name: Deployment Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd fastapi-book-project
            git pull origin main 
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            pip install fastapi || exit 1
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl stop fastapi
            killall uvicorn || echo “No existing process found”
            nohup uvicorn main:app --host 0.0.0.0 --port 8080 > app.log 2>&1 &
            echo “Application started successfully”