name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest changes
        run: |
          echo "Pulling latest changes..."
          git fetch --all
          git pull origin main

      - name: Setup virtual environment
        run: |
          echo "Setting up virtual environment..."
          python3 -m venv venv || exit 1
          source venv/bin/activate || exit 1

      - name: Install FastAPI
        run: |
          pip install fastapi || exit 1
          echo "FastAPI installed successfully"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt || exit 1

      - name: Stop existing application
        run: |
          echo "Stopping existing application..."
          killall uvicorn || echo "No existing process found"
          echo "Application stopped successfully"

      - name: Start application
        run: |
          echo "Starting application..."
          nohup uvicorn main:app --host 0.0.0.0 --port 8080 > app.log 2>&1 &
          echo "Application started successfully"
