name: CD Pipeline

on:
  push:
    branches: [ main ] 

jobs:
  deploy:   
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy api
      uses: actions/checkout@v4
      
    - name: Automatically update the deployed api with the latest changes
      uses: appleboy/ssh-action@master

      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "\
          cd /app && \
          git pull origin main && \
          pip install -r requirements.txt && \
          systemctl restart fastapi \
          sudo systemctl restart nginx"
